### ISSUE TITLE
mehrere Posts auf einer Page im Dropdown Menü

### ISSUE THREAD

**Issue by vorspelrueter** [CRC1266-A2/crc1266-a2.github.io#2]
Moin,
mein Problem ist momentan, dass die .md Posts die ich in dem Ordner _posts speichere immer auf der Hauptseite landen. Leider konnte ich auch durch diverse Youtube Videos nicht herausfinden, wie ich es hinbekommen, dass ich einer Page aus dem Dropdown Menü mehrere Posts zuweisen kann. Also z.B. hatte ich jetzt überlegt bei "Activities" einen Ordner mit "More" oder so anzulegen. Dort soll man dann mehrere Einträge finden können, und nicht nur einen. Bis jetzt habe ich es nur hinbekommen die Page mit einem bestimmten Post zu verlinken, das wird aber auf die Dauer wohl etwas unübersichtlich werden. Meine Überlegung war erst einen neuen Order namens "_more" zu erstellen und dort dann die verschiedenen .md Einträge zu speichern, die ich auf der "More" Seite haben möchte. Das hat aber nicht geklappt, da in der config.yml Datei die Navbar nicht darauf zu greifen konnte 
( activities:
      - More:  "_more" )

Könnt ihr mir da helfen? :)
Vielen Dank schon mal im voraus !

**Comment by dakni** [comment]
Salut.

Alles was den Dateinamen "Datum_Titel.md" hat kommt auf die Startseite (was ich auch gut so finde). Das sollte für alle activities gelten, denn ein potentieller Besucher möchte direkt Informationen sehen und nicht erst auf eine bestimmte Rubrik klicken ;)
