### ISSUE TITLE
integrate spaR repository into homepage

### ISSUE THREAD

**Issue by dakni** [CRC1266-A2/crc1266-a2.github.io#6]
the homepage of our modeling course (https://crc1266-a2.github.io/spaR/) should be implemented into the homepage...at best the layout of repo (https://github.com/CRC1266-A2/spaR) is the same like the general homepage [so the user does not recognize that she is on another url/repository]

**Comment by vorspelrueter** [comment]
alright ! in the making 

by the way:
1. Habe gerade festgestellt, dass der Link auf der CAU Seite von A2 (https://www.sfb1266.uni-kiel.de/de/teilprojekte/cluster-a/a2-integratives-modellieren) zu der neuen Seite nicht mehr stimmt. Der alte Link müsste hiermit ersetzt werden: https://crc1266-a2.github.io/Activities/. Ich würde dann Angelika Hoffmann schreiben, damit sie das ändert- die war unten als Kontakt für die Seiteninformation angegeben.
2. Musste ich gerade feststellen, dass das Layout der Seite sich verändert hat- oben und unten ist jetzt kein grauer Balken mehr + die einzelnen Beiträge sind nicht mehr durch Striche getrennt. Das gilt aber auch für die Original Beautiful Jekyll Seite- also hat der Kerl der die Seite erstellt hat wohl das Layout geändert und bei uns wurde es dann auch so übernommen. Ich versuche mal herauszufinden, ob man diese Verbindung beenden kann bzw. wie man das wieder zurücksetzen kann - außer euch gefällt es so, dann kann ich es natürlich auch so lassen :)

**Comment by dakni** [comment]
1) nice, danke.

2) strange...war das theme nur geforked?

**Comment by vorspelrueter** [comment]
noch komischer- das liegt nur an dem PC in der Uni. Habe einfach mal auf Verdacht mir das ganze von nem anderen PC aus angesehen und da sind sowohl unsere, als auch seine Originalseite immer noch so wie vorher. Also ist mit der Seite auf jeden Fall alles gut, mit dem PC weiß ich nicht so :D

**Comment by vorspelrueter** [comment]
update: liegt auch nur an dem linken Bildschirm- beim rechten Bildschirm sieht es normal aus. Mysteriös
